# Generated by Django 5.2 on 2025-07-24 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la dirección (ej: Casa, Trabajo, etc.)', max_length=100)),
                ('address_line', models.TextField(help_text='Dirección completa')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Latitud de la ubicación', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Longitud de la ubicación', max_digits=10)),
                ('is_default', models.BooleanField(default=False, help_text='Si es la dirección por defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Address',
                'verbose_name_plural': 'Delivery Addresses',
                'db_table': 'delivery_addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
