# Generated by Django 5.2 on 2025-07-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_deliveryaddress_options_deliveryaddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
