# Generated by Django 5.2 on 2025-07-24 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryaddress_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryaddress',
            options={},
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='is_default',
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='address_line',
            field=models.TextField(default='Dirección no especificada'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='name',
            field=models.CharField(default='Mi dirección', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to=settings.AUTH_USER_MODEL),
        ),
    ]
