# Generated by Django 5.2 on 2025-07-24 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('qr', 'QR Veripagos'), ('card', 'Tarjeta'), ('cash', 'Efectivo')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido'), ('expired', 'Expirado')], default='pending', max_length=20)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('qr_validity', models.CharField(default='1/00:00', max_length=20)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('sender_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sender_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_document', models.CharField(blank=True, max_length=50, null=True)),
                ('sender_account', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
