# Generated by Django 5.2 on 2025-04-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_url',
            field=models.TextField(blank=True),
        ),
    ]
