# Generated by Django 5.2 on 2025-04-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
