# Generated by Django 5.2 on 2025-04-13 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_sale_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sale.cashregister'),
        ),
    ]
