# Generated by Django 5.2 on 2025-04-22 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_photo_url'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('recommendation_type', models.CharField(choices=[('frequently_bought', 'Frecuentemente comprados juntos'), ('category', 'Misma categoría'), ('complementary', 'Complementario')], max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('recommended_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_as_target', to='inventory.product')),
                ('source_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_as_source', to='inventory.product')),
            ],
            options={
                'indexes': [models.Index(fields=['source_product', 'score'], name='user_produc_source__32cbfa_idx'), models.Index(fields=['recommended_product', 'score'], name='user_produc_recomme_f472fb_idx')],
                'unique_together': {('source_product', 'recommended_product')},
            },
        ),
    ]
